In [29]:
import pandas as pd

white_df = pd.read_csv("../data/winequality-white.csv", sep=";")
red_df = pd.read_csv("../data/winequality-red.csv", sep=";")

red_df['type']='red wine'
white_df['type']='white wine'
wine = pd.concat([red_df,white_df]).reset_index().drop(columns = ['index'])

In [30]:
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(wine, test_size=0.2, random_state=123)

In [31]:
train_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
6452,5.2,0.25,0.23,1.40,0.047,20.0,77.0,0.99001,3.32,0.62,11.4,5,white wine
5110,6.5,0.19,0.28,1.40,0.046,22.0,90.0,0.99038,3.18,0.51,11.7,7,white wine
2792,7.3,0.22,0.40,14.75,0.042,44.5,129.5,0.99980,3.36,0.41,9.1,7,white wine
1879,7.0,0.24,0.36,2.80,0.034,22.0,112.0,0.99000,3.19,0.38,12.6,8,white wine
2742,7.2,0.24,0.30,1.60,0.048,27.0,131.0,0.99330,3.25,0.45,10.5,5,white wine
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5218,6.8,0.45,0.28,26.05,0.031,27.0,122.0,1.00295,3.06,0.42,10.6,6,white wine
4060,8.2,0.26,0.33,2.60,0.053,11.0,71.0,0.99402,2.89,0.49,9.5,5,white wine
1346,6.1,0.59,0.01,2.10,0.056,5.0,13.0,0.99472,3.52,0.56,11.4,5,red wine
3454,8.0,0.22,0.28,14.00,0.053,83.0,197.0,0.99810,3.14,0.45,9.8,6,white wine
3582,7.6,0.20,0.30,14.20,0.056,53.0,212.5,0.99900,3.14,0.46,8.9,8,white wine

In [32]:
X_train = train_df.drop(columns=["quality"])
X_test = test_df.drop(columns=["quality"])
y_train = train_df["quality"]
y_test = test_df["quality"]

In [33]:
import numpy as np

In [34]:
numeric_feats = X_train.select_dtypes(include=[np.number]).columns.values.tolist()
binary_feats = ["type"]

In [35]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.compose import ColumnTransformer, make_column_transformer

In [36]:
numeric_transformer = make_pipeline(StandardScaler())
binary_transformer = make_pipeline(OneHotEncoder(drop="if_binary", dtype=int))

preprocessor = make_column_transformer(
    (numeric_transformer, numeric_feats),
    (binary_transformer, binary_feats)
)

In [37]:
column_name = numeric_feats + binary_feats

In [38]:
pd.DataFrame(preprocessor.fit_transform(X_train, y_train), columns = column_name)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,-1.552156,-0.537847,-0.616843,-0.849603,-0.256654,-0.599698,-0.688718,-1.550251,0.637496,0.602356,0.755569,1.0
1,-0.551023,-0.903607,-0.274431,-0.849603,-0.285082,-0.487984,-0.460217,-1.427678,-0.236615,-0.134424,1.005574,1.0
2,0.065059,-0.720727,0.547359,1.949924,-0.398798,0.768801,0.234073,1.692956,0.887242,-0.804224,-1.161136,1.0
3,-0.165971,-0.598807,0.273429,-0.556020,-0.626230,-0.487984,-0.073524,-1.553564,-0.174178,-1.005164,1.755589,1.0
4,-0.011951,-0.598807,-0.137466,-0.807663,-0.228225,-0.208698,0.260438,-0.460348,0.200441,-0.536304,0.005554,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5192,-0.319992,0.681350,-0.274431,4.319561,-0.711516,-0.208698,0.102245,2.736480,-0.985853,-0.737244,0.088889,1.0
5193,0.758151,-0.476888,0.067982,-0.597961,-0.086080,-1.102412,-0.794180,-0.221828,-2.047274,-0.268384,-0.827796,1.0
5194,-0.859063,1.534788,-2.123458,-0.702812,-0.000793,-1.437555,-1.813644,0.010066,1.886227,0.200476,0.755569,0.0
5195,0.604131,-0.720727,-0.274431,1.792647,-0.086080,2.919299,1.420518,1.129784,-0.486361,-0.536304,-0.577791,1.0
5196,0.296090,-0.842647,-0.137466,1.834587,-0.000793,1.243586,1.692961,1.427934,-0.486361,-0.469324,-1.327806,1.0